[Paths]
#处理路径
folder_path = E:\3陈忱\1协和学院\协和学院教学\考试\2024-2025下\Java程序设计\学生答卷
#学生学号
text_file_path = data\\3.txt
#需要过滤的文件.zip/.rar/.docx/.max
file_extension = .docx
#过滤的文件输出到文件夹output
output_folder = output
pdf_folder= pdf

[Params]
start_string = 124
check_dif_student_id_enabled = True
check_same_student_id_enabled = True
# 新增的配置项，指定要删除的后缀名，不需要删除则为空.log/.bak/.tmp/.jpg/.png/.PNG/.max/.rar
delete_extensions =.log/.bak/.tmp/.jpg/.png/.PNG/.max/.rar